### ISSUE TITLE
Get rid of the support block

### ISSUE THREAD

**Issue by robertDouglass** [LaconicNetwork/Laconic-Documentation#41]
```
Still Didn’t Find Your Answer?
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
```

**Comment by christophberger** [comment]
This block is defined in `config.toml`:

```toml
# call to action
[Languages.en.call_to_action]
enable = true
title = "Still Didn't Find Your Answer?"
image = "images/cta-illustration.jpg"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

  # call to action button
  [Languages.en.call_to_action.button]
  enable = true
  label = "Submit a ticket"
  link = "contact"
```
